spring:
  application:
    name: ${SPRING_APP_NAME:spring-security-demo}
  config:
    import: application-prod.yml
  profiles:
    active: default
  security:
    user:
      name: ${SECURITY_USERNAME:hieptt149}
      password: ${SECURITY_PASSWORD:12345}
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${INTROSPECT_URI:http://localhost:8180/realms/eazybankdev/protocol/openid-connect/token/introspect}
          client-id: ${INTROSPECT_ID:eazybankintrospect}
          client-secret: ${INTROSPECT_SECRET:BVm2wB0l63GXKmqRQL8xL2PEPT71HlUr}
        #jwt:
          #jwk-set-uri: ${JWK_SET_URI:http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}
